### List tasks
GET http://localhost:3000/tasks HTTP/1.1

### Get task by ID
GET http://localhost:3000/tasks/2 HTTP/1.1

### Create a new task
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Another task",
  "completed": false
}

### Update a task
PUT http://localhost:3000/tasks/2 HTTP/1.1
Content-Type: application/json

{
  "title": "Updated task title",
  "completed": true
}

### Delete a task
DELETE http://localhost:3000/tasks/2 HTTP/1.1